import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

export function slugify(input: string): string {
  return input
    .normalize('NFKD')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
}

function getRepo() {
  const owner = process.env.GITHUB_REPO_OWNER;
  const name = process.env.GITHUB_REPO_NAME;
  const token = process.env.GITHUB_TOKEN;
  if (!owner || !name || !token) {
    throw new Error('GITHUB_REPO_OWNER, GITHUB_REPO_NAME and GITHUB_TOKEN must be set');
  }
  return { owner, name, token };
}

async function gh(path: string, init?: RequestInit): Promise<{ ok: boolean; status: number; data: any }> {
  const { owner, name, token } = getRepo();
  const url = `https://api.github.com/repos/${owner}/${name}/${path}`;
  const res = await fetch(url, {
    ...init,
    headers: {
      Accept: 'application/vnd.github+json',
      Authorization: `Bearer ${token}`,
      'X-GitHub-Api-Version': '2022-11-28',
      ...(init?.headers ?? {}),
    },
  });
  const text = await res.text();
  let data: any = null;
  try {
    data = text ? JSON.parse(text) : null;
  } catch {
    data = text;
  }
  return { ok: res.ok, status: res.status, data };
}

function isLocalMode(): boolean {
  return process.env.PUBLISH_MODE === 'local';
}

function localPath(relPath: string): string {
  return resolve(process.cwd(), relPath);
}

export async function fileExists(path: string): Promise<boolean> {
  if (isLocalMode()) {
    return existsSync(localPath(path));
  }
  const res = await gh(`contents/${path}`);
  return res.status === 200;
}

export async function readFile(path: string): Promise<{ content: string; sha: string } | null> {
  if (isLocalMode()) {
    try {
      return { content: readFileSync(localPath(path), 'utf8'), sha: '' };
    } catch {
      return null;
    }
  }
  const res = await gh(`contents/${path}`);
  if (res.status !== 200) return null;
  return {
    content: Buffer.from(res.data.content, 'base64').toString('utf8'),
    sha: res.data.sha,
  };
}

export async function createUniqueSlug(base: string, dir: string): Promise<string> {
  const slug = slugify(base) || 'untitled';
  let candidate = slug;
  let n = 2;
  while (await fileExists(`${dir}/${candidate}.md`)) {
    candidate = `${slug}-${n}`;
    n += 1;
  }
  return candidate;
}

interface WriteViaPrArgs {
  path: string;
  content: string;
  message: string;
}

/**
 * Write a markdown file to the repo and publish it by opening a PR that is
 * auto-merged. The admin never touches git — this is invoked by the system
 * when content is approved or published.
 *
 * With `PUBLISH_MODE=local` (development), the file is written directly into
 * the local repository so the flow can be tested without GitHub.
 */
export async function writeFileViaPr({ path, content, message }: WriteViaPrArgs): Promise<{ url: string }> {
  if (isLocalMode()) {
    const fullPath = localPath(path);
    mkdirSync(dirname(fullPath), { recursive: true });
    writeFileSync(fullPath, content, 'utf8');
    console.log(`[publish:local] ${message}\n  -> ${path}`);
    return { url: path };
  }

  const mainRef = await gh(`git/ref/heads/main`);
  if (mainRef.status !== 200) throw new Error(`Could not resolve main branch: ${JSON.stringify(mainRef.data)}`);
  const baseSha = mainRef.data.object.sha;

  const branch = `auto/${Date.now()}`;
  const refRes = await gh(`git/refs`, {
    method: 'POST',
    body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: baseSha }),
  });
  if (refRes.status !== 201) throw new Error(`Could not create branch: ${JSON.stringify(refRes.data)}`);

  // If the file already exists on main, include its sha so the contents API
  // updates it instead of erroring (covers re-publishing / re-approving).
  const existing = await readFile(path);
  const putBody: Record<string, unknown> = {
    message,
    content: Buffer.from(content, 'utf8').toString('base64'),
    branch,
  };
  if (existing?.sha) putBody.sha = existing.sha;

  const putRes = await gh(`contents/${path}`, {
    method: 'PUT',
    body: JSON.stringify(putBody),
  });
  if (putRes.status !== 201 && putRes.status !== 200) {
    throw new Error(`Could not write file: ${JSON.stringify(putRes.data)}`);
  }

  const prRes = await gh(`pulls`, {
    method: 'POST',
    body: JSON.stringify({
      title: message,
      head: branch,
      base: 'main',
      body: `Auto-generated by QRNLab site system.\n\nPath: \`${path}\``,
    }),
  });
  if (prRes.status !== 201) throw new Error(`Could not open PR: ${JSON.stringify(prRes.data)}`);

  const mergeRes = await gh(`pulls/${prRes.data.number}/merge`, {
    method: 'PUT',
    body: JSON.stringify({ merge_method: 'squash' }),
  });
  if (!mergeRes.ok) {
    throw new Error(`Could not auto-merge PR: ${JSON.stringify(mergeRes.data)}`);
  }

  return { url: prRes.data.html_url };
}

/**
 * Update an existing file on main directly (for editing already-published content).
 */
export async function updateFileOnMain(path: string, content: string, sha: string, message: string): Promise<void> {
  if (isLocalMode()) {
    const fullPath = localPath(path);
    mkdirSync(dirname(fullPath), { recursive: true });
    writeFileSync(fullPath, content, 'utf8');
    console.log(`[publish:local] ${message}\n  -> ${path}`);
    return;
  }
  const res = await gh(`contents/${path}`, {
    method: 'PUT',
    body: JSON.stringify({
      message,
      content: Buffer.from(content, 'utf8').toString('base64'),
      sha,
    }),
  });
  if (res.status !== 200) throw new Error(`Could not update file: ${JSON.stringify(res.data)}`);
}
