// Generated by filesystem-routing. Do not edit.
// Regenerated whenever a route file is added, changed or removed.

declare module "virtual:file-routes" {
  /** A code-split ref: the delivery adapter emits it as a dynamic import. */
  export interface FileRouteLazyRef<M = Record<string, unknown>> {
    src: string;
    import(): Promise<M>;
  }

  /** An eager ref: its picked exports are imported statically. */
  export interface FileRouteEagerRef<M = Record<string, unknown>> {
    /** The source module path — present when the convention emitted the ref lazy and `codeSplitting: false` delivered it eagerly. */
    src?: string;
    require(): M;
  }

  /** A flat entry of the route manifest. */
  export interface FileRouteEntry {
    path: string;
    page?: boolean;
    $component?: FileRouteLazyRef<any> | FileRouteEagerRef<any>;
    $$route?: FileRouteEagerRef<any>;
    [key: string]: unknown;
  }

  /** An entry of the nested `pageRoutes` view. */
  export interface FileRouteTreeEntry extends FileRouteEntry {
    id: string;
    children?: readonly FileRouteTreeEntry[];
  }

  /** The flat route manifest, in scan order. */
  const routes: readonly [
    {
      path: "/account";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/account")>;
      $$route?: undefined;
    },
    {
      path: "/blog";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/blog")>;
      $$route?: undefined;
    },
    {
      path: "/education";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/education")>;
      $$route?: undefined;
    },
    {
      path: "/forgot-password";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/forgot-password")>;
      $$route?: undefined;
    },
    {
      path: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/index")>;
      $$route?: undefined;
    },
    {
      path: "/join";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/join")>;
      $$route?: undefined;
    },
    {
      path: "/login";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/login")>;
      $$route?: undefined;
    },
    {
      path: "/media";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/media")>;
      $$route?: undefined;
    },
    {
      path: "/publications";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/publications")>;
      $$route?: undefined;
    },
    {
      path: "/reset-password";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/reset-password")>;
      $$route?: undefined;
    },
    {
      path: "/team";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/team")>;
      $$route?: undefined;
    },
    {
      path: "/updates";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/updates")>;
      $$route?: undefined;
    },
    {
      path: "/users";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/users")>;
      $$route?: undefined;
    },
    {
      path: "/account/edit";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/account/edit")>;
      $$route?: undefined;
    },
    {
      path: "/account/posts";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/account/posts")>;
      $$route?: undefined;
    },
    {
      path: "/blog/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/blog/[id]")>;
      $$route?: undefined;
    },
    {
      path: "/blog/new";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/blog/new")>;
      $$route?: undefined;
    }
  ];
  export default routes;

  /** The page entries, nested by path with grouping segments stripped. */
  export const pageRoutes: readonly [
    {
      path: "/";
      id: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/blog";
      id: "/blog";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/blog")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/:id";
          id: "/:id";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/blog/[id]")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/new";
          id: "/new";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/blog/new")>;
          $$route?: undefined;
          children?: undefined;
        }
      ];
    },
    {
      path: "/join";
      id: "/join";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/join")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/team";
      id: "/team";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/team")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/login";
      id: "/login";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/login")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/media";
      id: "/media";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/media")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/users";
      id: "/users";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/users")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/account";
      id: "/account";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/account")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/edit";
          id: "/edit";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/account/edit")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/posts";
          id: "/posts";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/account/posts")>;
          $$route?: undefined;
          children?: undefined;
        }
      ];
    },
    {
      path: "/updates";
      id: "/updates";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/updates")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/education";
      id: "/education";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/education")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/publications";
      id: "/publications";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/publications")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/reset-password";
      id: "/reset-password";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/reset-password")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/forgot-password";
      id: "/forgot-password";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/forgot-password")>;
      $$route?: undefined;
      children?: undefined;
    }
  ];
}
